parameters:
#    cagunademo.example.class: caguna\demoBundle\Example

services:
#    cagunademo.example:
#        class: %cagunademo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    cagunademo.user_manager:
        class: caguna\demoBundle\Domain\UserManager
        arguments: [doctrine.entity_manager]
